src/objects/Brand__c.object
<CustomObject>
    <description>Brand</description>
    <fields>
        <fullName>EnterpriseID__c</fullName>
        <externalId>true</externalId>
        <label>EnterpriseID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Manufacturer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Manufacturer</description>
        <inlineHelpText>Manufacturer</inlineHelpText>
        <label>Manufacturer</label>
        <referenceTo>MDM_Manufacturer__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MDM_Brand__c.object
<CustomObject>
    <description>Brand</description>
    <fields>
        <fullName>EnterpriseID__c</fullName>
        <externalId>true</externalId>
        <label>EnterpriseID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Manufacturer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Manufacturer</description>
        <inlineHelpText>Manufacturer</inlineHelpText>
        <label>Manufacturer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>MDM_Manufacturer__c.EnterpriseID__c</field>
                <operation>startsWith</operation>
                <value>MG-</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>MDM_Manufacturer__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MDM_Configuration__c.object
<CustomObject>
    <description>The object contains all configuration values for MDM Location Reference app.</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>This field used to describe the row.</description>
        <inlineHelpText>This will be used When the value is too big.</inlineHelpText>
        <label>Description</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>This is for the configuration field(a) Name &amp; Value pairs. 
Name stored in Name and the  values stored here.</description>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MDM_Configuration</label>
    <nameField>
        <label>MDM_Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MDM_Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MDM_Manufacturer__c.object
<CustomObject>
    <description>Manufacturer</description>
    <fields>
        <fullName>EnterpriseID__c</fullName>
        <description>EnterpriseID</description>
        <externalId>true</externalId>
        <inlineHelpText>EnterpriseID</inlineHelpText>
        <label>EnterpriseID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Manufacturer</label>
    <nameField>
        <label>Manufacturer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manufacturers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MDM_ManufacturerProductCategory__c.object
<CustomObject>
    <description>ManufacturerProductCategory</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description</description>
        <inlineHelpText>Description</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EnterpriseID__c</fullName>
        <description>EnterpriseID</description>
        <inlineHelpText>EnterpriseID</inlineHelpText>
        <label>EnterpriseID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manufacturer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Product Manufacturer</description>
        <inlineHelpText>Product Manufacturer</inlineHelpText>
        <label>Manufacturer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>MDM_Manufacturer__c.EnterpriseID__c</field>
                <operation>startsWith</operation>
                <value>MG-</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>MDM_Manufacturer__c</referenceTo>
        <relationshipLabel>ManufacturerProductCategories</relationshipLabel>
        <relationshipName>ManufacturerProductCategories</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>ManufacturerProductCategory</label>
    <nameField>
        <label>ManufacturerProductCategory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ManufacturerProductCategories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MDM_Product__c.object
<CustomObject>
    <description>MDM_Product</description>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>MDM_Brand__c.Manufacturer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Manufacturer__c</valueField>
            </filterItems>
            <filterItems>
                <field>MDM_Brand__c.EnterpriseID__c</field>
                <operation>startsWith</operation>
                <value>BD</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>MDM_Brand__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CategoryFamilyName__c</fullName>
        <formula>Category__r.CategoryFamilyName__c</formula>
        <label>CategoryFamilyName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Product Description</description>
        <inlineHelpText>Product Description</inlineHelpText>
        <label>Description</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EnterpriseID__c</fullName>
        <description>EnterpriseID</description>
        <externalId>true</externalId>
        <label>EnterpriseID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Manufacturer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Manufacturer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>MDM_Manufacturer__c.EnterpriseID__c</field>
                <operation>startsWith</operation>
                <value>MG-</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>MDM_Manufacturer__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Status__c</fullName>
        <label>Product Status</label>
        <picklist>
            <picklistValues>
                <fullName>Future</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discontinued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UPC12__c</fullName>
        <description>Universal Product Code</description>
        <inlineHelpText>Universal Product Code
This is the 12 digit UPC-A. Note, one of the five identifying numbers must be specified</inlineHelpText>
        <label>UPC-12</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <label>MDM_Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MDM_Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MDM_Product_Country__c.object
<CustomObject>
    <fields>
        <fullName>EnterpriseID__c</fullName>
        <label>EnterpriseID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>MDM_Product_Country</label>
    <nameField>
        <label>MDM_Product_Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MDM_Product_Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MDM_Product_Group__c.object
<CustomObject>
    <description>Product Group</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EnterpriseID__c</fullName>
        <externalId>true</externalId>
        <label>EnterpriseID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Manufacturer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Manufacturer</description>
        <inlineHelpText>Manufacturer</inlineHelpText>
        <label>Manufacturer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>MDM_Manufacturer__c.EnterpriseID__c</field>
                <operation>startsWith</operation>
                <value>MG-</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>MDM_Manufacturer__c</referenceTo>
        <relationshipLabel>Product Groups</relationshipLabel>
        <relationshipName>Product_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MDM_ProductCategory__c.object
<CustomObject>
    <description>This is actually what we will refer to as the category and the value that will be shown in the product UI</description>
    <fields>
        <fullName>CategoryFamilyName__c</fullName>
        <description>This is True Category family name for a set of categories</description>
        <inlineHelpText>This is True Category family name for a set of categories</inlineHelpText>
        <label>CategoryFamilyName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EnterpriseID__c</fullName>
        <externalId>true</externalId>
        <label>EnterpriseID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Product SubCategory</label>
    <nameField>
        <label>CategoryName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product SubCategory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MDM_Source__c.object
<CustomObject>
    <description>This object is to have he list of source for MDM.
When a record send to BOOMI MDM for mastering all records should have this reference,
To determine, who is the contributor for the system of record source.</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Row description</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Domain__c</fullName>
        <label>Domain</label>
        <picklist>
            <picklistValues>
                <fullName>MDM_Location</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>MDM_Product</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>EnableBulkupload__c</fullName>
        <defaultValue>false</defaultValue>
        <description>EnableBulkupload</description>
        <inlineHelpText>EnableBulkupload</inlineHelpText>
        <label>EnableBulkupload</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SourceCode__c</fullName>
        <externalId>true</externalId>
        <label>SourceCode</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>MDM_Source</label>
    <nameField>
        <label>MDM_Source Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MDM_Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MDM_Product_All_Reference_Test.cls
@IsTest
public class MDM_Product_All_Reference_Test {
    @istest
    Static void MDM_Product_All_Reference_Test()
    {
        
        MDM_Configuration__c mdc = new MDM_Configuration__c();
        mdc.name='MDM_IntegrationUser';
        mdc.Value__c = 'Ramakrishnan.Ramadur@crossmark.com.mdmlocuat' ;
        insert mdc;
        
        MDM_Configuration__c mdc0 = new MDM_Configuration__c();
        mdc0.name='DeleteStageRecordsBeforeInsert';
        mdc0.Value__c = 'true' ;
        insert mdc0;
        
        MDM_Configuration__c mdc00 = new MDM_Configuration__c();
        mdc00.name='TemplateName';
        mdc00.Value__c = 'MDM_Location_Bulkupload_Temlate' ;
        insert mdc00;
        
        MDM_Configuration__c mdc1 = new MDM_Configuration__c();
        mdc1.name='BatchUploadHeaderLine';
        mdc1.Value__c = 'Type|Number|Status|Name|Address line 1:|Address line 2:|Address line 3:|City|State|Country|Postal Code|Phone Number|Fax Number|Latitude|Longitude|Owning Company|Chain|Franchiser|TradeChannel|TradeSubchannel|TDLinxNO|IdFromSource' ;
        insert mdc1;
        
        MDM_Configuration__c mdc2 = new MDM_Configuration__c();
        mdc2.name='BatchUploadDelimiter';
        mdc2.Value__c = '|' ;
        insert mdc2;
        
        
        
        MDM_Source__c lsc = new MDM_Source__c();
        lsc.Name = 'SalesForce-Product';
        lsc.SourceCode__c = 'CMKPSF';
        lsc.EnableBulkupload__c=true;
        lsc.Domain__c='MDM_Product';
        insert(lsc);
        
        MDM_Manufacturer__c mfg0 = new MDM_Manufacturer__c();
        mfg0.Name = 'Test Manufacturer0';
        mfg0.EnterpriseID__c = 'MG-01';
        insert(mfg0);
        
        MDM_Manufacturer__c mfg1 = new MDM_Manufacturer__c();
        mfg1.Name = 'Test Manufacturer1';
        mfg1.EnterpriseID__c = 'MG-02';
        insert(mfg1);
        
        MDM_Manufacturer__c mfg3 = new MDM_Manufacturer__c();
        mfg3.Name = 'Test Manufacturer3';
        insert(mfg3);
        mfg3.Name = 'Test Manufacturer3-updated';
        update(mfg3);
        try{
            mfg3.Name = 'Test Manufacturer0'; //try duplicate update
            update(mfg3);    
        }catch(Exception ex){}
        
        
        
        MDM_Brand__C bra0 = new MDM_Brand__C();
        bra0.Name = 'Test Manufacturer0-Bra0';
        bra0.Manufacturer__C = mfg0.id;
        bra0.EnterpriseID__c = 'BD-01';
        insert(bra0);
        
        MDM_Brand__C bra1 = new MDM_Brand__C();
        bra1.Name = 'Test Manufacturer1-Bra1';
        bra1.Manufacturer__C = mfg1.id;
        bra1.EnterpriseID__c = 'BD-02';
        insert(bra1);
        
        MDM_Brand__C bra3 = new MDM_Brand__C();
        bra3.Name = 'Test Manufacturer1-Bra3';
        bra3.Manufacturer__C = mfg1.id;
        
        insert(bra3);
        bra3.Name = 'Test Manufacturer1-Bra3-updated';
        update(bra3);
        try{
            bra3.Name = 'Test Manufacturer1-Bra1';
            update(bra3);
        }catch(Exception ex){}
        
        
        MDM_Product_Group__c pg0= new MDM_Product_Group__c();
        pg0.Name = 'Test Manufacturer1- PRGRP 0';
        pg0.Manufacturer__C = mfg1.id;
        pg0.EnterpriseID__c = 'PG-01';
        insert(pg0);
        
        
        MDM_Product_Group__c pg1= new MDM_Product_Group__c();
        pg1.Name = 'Test Manufacturer1- PRGRP 1';
        pg1.Manufacturer__C = mfg1.id;
        pg1.EnterpriseID__c = 'PG-02';
        insert(pg1);
        
        MDM_Product_Group__c pg3= new MDM_Product_Group__c();
        pg3.Name = 'Test Manufacturer1- PRGRP3';
        pg3.Manufacturer__C = mfg1.id;
        insert(pg3);
        pg3.Name = 'Test Manufacturer1- PRGRP3-updated';
        update(pg3);
        try{
            pg3.Name = 'Test Manufacturer1- PRGRP 1';
            update(pg3); 
        }catch(Exception ex){}
        
        
        
        MDM_ProductCategory__c pc1= new MDM_ProductCategory__c();
        pc1.Name = 'ProductCategory 1';
        pc1.CategoryFamilyName__c = 'ProductCategory - Family1';
        pc1.EnterpriseID__c = 'PC-01';
        insert(pc1);
        
        MDM_ProductCategory__c pc2= new MDM_ProductCategory__c();
        pc2.Name = 'ProductCategory 2';
        pc2.CategoryFamilyName__c = 'ProductCategory - Family2';
        insert(pc2);
        
        pc2.Name = 'ProductCategory 2- updated';
        update(pc2);
        try{
            pc2.Name = 'ProductCategory 1';
            update(pc2);
        }catch(Exception ex){}
        
        
        
        MDM_ManufacturerProductCategory__c mpc0= new MDM_ManufacturerProductCategory__c();
        mpc0.Name = 'Test Manufacturer ProductCategory  MPC1 ';
        mpc0.Manufacturer__C = mfg1.id;
        mpc0.EnterpriseID__c = 'MC-01';
        insert(mpc0);
        
        
        MDM_ManufacturerProductCategory__c mpc1= new MDM_ManufacturerProductCategory__c();
        mpc1.Name = 'Test Manufacturer ProductCategory  MPC2';
        mpc1.Manufacturer__C = mfg1.id;
        mpc1.EnterpriseID__c = 'MC-02';
        insert(mpc1);
        
        MDM_ManufacturerProductCategory__c mpc3= new MDM_ManufacturerProductCategory__c();
        mpc3.Name = 'Test Manufacturer ProductCategory  MPC3';
        mpc3.Manufacturer__C = mfg1.id;
        insert(mpc3);
        mpc3.Name = 'Test Manufacturer ProductCategory  MPC3 - updated';
        update(mpc3);
        try{
            mpc3.Name = 'Test Manufacturer ProductCategory  MPC1';
            update(mpc3);
        }catch(Exception ex){}
        
        
        MDM_Product_Country__c c0 = new MDM_Product_Country__c();
        c0.Name='UNITED STATES';
        c0.EnterpriseID__c= 'CN-0001';
        insert(c0);
        MDM_Product_Country__c c1 = new MDM_Product_Country__c();
        c1.Name='CANADA';
        c1.EnterpriseID__c= 'CN-002';
        insert(c1);
        
        
        try{
            c0.Name='CANADA -1 ';
            update(c0);
        }catch(Exception ex){}
        
        
        MDM_Product__c  p0	= new MDM_Product__c();
        p0.name= 'Test Product1';
        p0.Manufacturer__c = mfg0.id;
        p0.Brand__c = bra0.id;
        p0.Product_Status__c = 'Active';
        p0.Short_Description__c = 'Test Product1';
        p0.Description__c='Test Product1';
        p0.UPC12__c = '233333324233';
        p0.Is_Shipping_Product__c = true;
        
        insert p0;
        p0.name= 'Test Product1-updated';
        update p0;
        try{
        p0.UPC12__c = '23333924233';
        }catch(Exception ex){}
        
        
        delete(mpc3);
        delete(pc2);
        delete(pg3);
        delete(bra3);
        delete(mfg3);
   
        
        
        Test.startTest();
        
        
        
        Test.stopTest();  
    }
}