src/objects/Brand__c.object
<CustomObject>
    <description>Brand</description>
    <fields>
        <fullName>Manufacturer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Manufacturer</description>
        <inlineHelpText>Manufacturer</inlineHelpText>
        <label>Manufacturer</label>
        <referenceTo>MDM_Manufacturer__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MDM_Product__c.object
<CustomObject>
    <description>MDM_Product</description>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>MDM_Brand__c.Manufacturer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Manufacturer__c</valueField>
            </filterItems>
            <filterItems>
                <field>MDM_Brand__c.EnterpriseID__c</field>
                <operation>startsWith</operation>
                <value>BD</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>MDM_Brand__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>MDM_ProductCategory__c.EnterpriseID__c</field>
                <operation>startsWith</operation>
                <value>PC</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>MDM_ProductCategory__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CustomizedLastModifiedDatetime__c</fullName>
        <defaultValue>$System.OriginDateTime</defaultValue>
        <description>CustomizedLastModifiedDatetime</description>
        <inlineHelpText>CustomizedLastModifiedDatetime</inlineHelpText>
        <label>CustomizedLastModifiedDatetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CustomizedLastModifiedUserName__c</fullName>
        <description>CustomizedLastModifiedUserName</description>
        <inlineHelpText>Who Last updated the Product / Added or updated a Reference to this product.</inlineHelpText>
        <label>CustomizedLastModifiedUserName</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ManufacturerCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ManufacturerProductCategory</description>
        <inlineHelpText>ManufacturerProductCategory</inlineHelpText>
        <label>ManufacturerCategory</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>MDM_ManufacturerProductCategory__c.Manufacturer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Manufacturer__c</valueField>
            </filterItems>
            <filterItems>
                <field>MDM_ManufacturerProductCategory__c.EnterpriseID__c</field>
                <operation>startsWith</operation>
                <value>MC</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>MDM_ManufacturerProductCategory__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manufacturer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Manufacturer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>MDM_Manufacturer__c.EnterpriseID__c</field>
                <operation>startsWith</operation>
                <value>MG-</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>MDM_Manufacturer__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Country</label>
        <referenceTo>MDM_Product_Country__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>MDM_Product_Group__c.Manufacturer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Manufacturer__c</valueField>
            </filterItems>
            <filterItems>
                <field>MDM_Product_Group__c.EnterpriseID__c</field>
                <operation>startsWith</operation>
                <value>PG</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>MDM_Product_Group__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MDM_Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MDM_Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Group__c.object
<CustomObject>
    <description>Product Group</description>
    <fields>
        <fullName>Manufacturer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Manufacturer</description>
        <inlineHelpText>Manufacturer</inlineHelpText>
        <label>Manufacturer</label>
        <referenceTo>MDM_Manufacturer__c</referenceTo>
        <relationshipLabel>Product Groups</relationshipLabel>
        <relationshipName>Product_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MDM_Product_Reference_UpdatedBt.cls
global with sharing class MDM_Product_Reference_UpdatedBt implements Database.Batchable<MDM_Product__c>,Database.Stateful{    
    global list<MDM_Product__c> blList;
    global String refobjName;
    global id refObjId;
    global String lstmodusr;
    
    global MDM_Product_Reference_UpdatedBt(string prefobjName, id prefObjId, string plstmodusr){
        refobjName = prefobjName;
        refObjId=prefObjId;
        lstmodusr = plstmodusr;
    }
    
    global Iterable<MDM_Product__c> start(Database.BatchableContext BC){
        blList = new  list<MDM_Product__c>();
        if(refobjName == 'Manufacturer')
        {
             blList = [select Id ,name,CustomizedLastModifiedUserName__c,CustomizedLastModifiedDatetime__c  from MDM_Product__c  where  Manufacturer__c =: refObjId limit 10000];
        }
        if(refobjName == 'Brand')
        {
             blList = [select Id ,name,CustomizedLastModifiedUserName__c,CustomizedLastModifiedDatetime__c  from MDM_Product__c  where  Brand__c =: refObjId limit 10000];
        }
        if(refobjName == 'ProductGroup')
        {
             blList = [select Id ,name,CustomizedLastModifiedUserName__c,CustomizedLastModifiedDatetime__c  from MDM_Product__c  where  Product_Group__c =: refObjId limit 10000];
        }
        if(refobjName == 'ProductCategory')
        {
             blList = [select Id ,name,CustomizedLastModifiedUserName__c,CustomizedLastModifiedDatetime__c  from MDM_Product__c  where  Category__c =: refObjId limit 10000];
        }
        if(refobjName == 'ManufacturerProductCategory')
        {
             blList = [select Id ,name,CustomizedLastModifiedUserName__c,CustomizedLastModifiedDatetime__c  from MDM_Product__c  where  ManufacturerCategory__c   =: refObjId limit 10000];
        }
        if(refobjName == 'ProductCountry')
        {
             blList = [select Id ,name,CustomizedLastModifiedUserName__c,CustomizedLastModifiedDatetime__c  from MDM_Product__c  where  Product_Country__c   =: refObjId limit 10000];
        }
        return blList;
    }
    global void execute(Database.BatchableContext BC, List<MDM_Product__c> scope){
        try
        {
            for(MDM_Product__c  q: scope) 
            {
 
            q.CustomizedLastModifiedUserName__c = lstmodusr;
            Datetime cDT = System.now();    
            q.CustomizedLastModifiedDatetime__c = cDT;
            update(q); 
                
            }
        }
        catch(Exception e)
        {
            System.debug('==Exception Message === MDM_Product_Reference_UpdatedBt '+e.getMessage());
             
        }
        
    }
    global void finish(Database.BatchableContext BC){
        try
        {
             
        }
        catch(System.EmailException ex){
            system.debug('============== email exception caught!!!=============');
        }
 
    }
 
}