src/objects/MDM_ManufacturerProductCategory__c.object
<CustomObject>
    <description>ManufacturerProductCategory</description>
    <fields>
        <fullName>EnterpriseID__c</fullName>
        <description>EnterpriseID</description>
        <inlineHelpText>EnterpriseID</inlineHelpText>
        <label>EnterpriseID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ManufacturerProductCategoryID__c</fullName>
        <description>This ID will be EnterpriseID.Whereas Data steward has control over the org refresh.</description>
        <displayFormat>MC-{000000000}</displayFormat>
        <inlineHelpText>This ID will be EnterpriseID.Whereas Data steward has control over the org refresh.</inlineHelpText>
        <label>ManufacturerProductCategoryID</label>
        <type>AutoNumber</type>
    </fields>
    <label>ManufacturerProductCategory</label>
    <nameField>
        <label>ManufacturerProductCategory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ManufacturerProductCategories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MDM_ProductCategory__c.object
<CustomObject>
    <description>This is actually what we will refer to as the category and the value that will be shown in the product UI</description>
    <fields>
        <fullName>EnterpriseID__c</fullName>
        <externalId>true</externalId>
        <label>EnterpriseID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Product SubCategory</label>
    <nameField>
        <label>CategoryName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product SubCategory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MDM_Product_Mfg_PrdCategory_PopulateIDBt.cls
global with sharing  class MDM_Product_Mfg_PrdCategory_PopulateIDBt implements Database.Batchable<MDM_ManufacturerProductCategory__c>, Database.Stateful {
    global list<MDM_ManufacturerProductCategory__c> blList;
    string  strcountSOQL = '';
    string rid = '';
    
    global MDM_Product_Mfg_PrdCategory_PopulateIDBt(){
        // To populate the EnrterpriseID from the Auto generated ProductCategory ID
        // rList = [select Id ,name,ManufacturerProductCategoryID__c,EnterpriseID__c  from MDM_ProductCategory__c  where id=:l.id];
    }
    global Iterable<MDM_ManufacturerProductCategory__c> start(Database.BatchableContext BC){
        blList = new list<MDM_ManufacturerProductCategory__c>();
        blList = [select Id ,name,ManufacturerProductCategoryID__c,EnterpriseID__c  from MDM_ManufacturerProductCategory__c  where  EnterpriseID__c = null or EnterpriseID__c =  ' '   limit 5];
        
        return blList;
    }
    
    global void execute(Database.BatchableContext BC, List<MDM_ManufacturerProductCategory__c> scope){
        try
        {
            for(MDM_ManufacturerProductCategory__c  l: scope) 
            {
                list<MDM_ManufacturerProductCategory__c> rList = new list<MDM_ManufacturerProductCategory__c>();
                rList = [select Id ,name,ManufacturerProductCategoryID__c,EnterpriseID__c  from MDM_ManufacturerProductCategory__c  where id=:l.id];
                if(rList.size() !=0)
                {
                    MDM_ManufacturerProductCategory__c a = rList[0];
                    a.EnterpriseID__c = a.ManufacturerProductCategoryID__c;
                    update a;
                }
                
            }
        }
        catch(Exception e)
        {
            System.debug('==Exception Message === MDM_Product_Mfg_PrdCategory_PopulateIDBt '+e.getMessage());
             
        }
    }
    public void finish(Database.BatchableContext BC){

    }
}